title: FractumSeraph
author:
  name: FractumSeraph
  email: web@fractumseraph.net
description: Where I sometimes post things.
theme: hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: classic
