title: FractumSeraph
author:
  name: FractumSeraph
  email: web@fractumseraph.net
description: Where I sometimes post things.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - about.md
