title: FractumSeraph
author:
  name: FractumSeraph
  email: web@fractumseraph.net
description: Where I sometimes post things.
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - about.md
minima:
  skin: classic
remote_theme: pages-themes/hacker@v0.2.0
