title: FractumSeraph
author:
  name: FractumSeraph
  email: web@fractumseraph.net
description: Where I sometimes post things.
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - github-pages
  - jekyll-theme-hacker
header_pages:
  - about.md
